---
- name: create user
  user: name=zabbix home={{ zabbix_installdir }} createhome=no system=yes

- name: change owner of installation directory
  file: path={{ zabbix_installdir }} recurse=yes owner=zabbix

- name: add agentd binary to PATH
  file: path=/usr/local/sbin/zabbix_agentd src={{ zabbix_installdir }}/sbin/zabbix_agentd state=link

- name: register service
  shell: chdir={{ zabbix_sourcedir }}/misc/init.d/debian/ cp * /etc/init.d/

- name: configure ServerActive to be {{ zabbix_server }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_agentd.conf regexp="^ServerActive=.*" line='ServerActive={{ zabbix_server }}'
- name: configure Server to be {{ zabbix_server }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_agentd.conf regexp="^Server=.*" line='Server={{ zabbix_server }}'
- name: configure Hostname to be {{ ansible_hostname }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_agentd.conf regexp="^Hostname=.*" line='Hostname={{ ansible_hostname }}'
