---
- name: create user
  user: name=zabbix home={{ zabbix_installdir }} createhome=no system=yes

- name: create proxy cachebase directory
  file: path={{ zabbix_installdir }}/var state=directory

- name: change owner of installation directory
  file: path={{ zabbix_installdir }} recurse=yes owner=zabbix

- name: add proxy binary to PATH
  file: path=/usr/local/sbin/zabbix_proxy src={{ zabbix_installdir }}/sbin/zabbix_proxy state=link
- name: add agentd binary to PATH
  file: path=/usr/local/sbin/zabbix_agentd src={{ zabbix_installdir }}/sbin/zabbix_agentd state=link

- name: register services
  shell: chdir={{ zabbix_sourcedir }}/misc/init.d/debian/ cp * /etc/init.d/

- name: link proxy service
  file: path=/etc/init.d/zabbix-proxy src=/etc/init.d/zabbix-server state=link

- name: configure proxy service name
  lineinfile: dest=/etc/init.d/zabbix-proxy regexp="^NAME=.*" line='NAME=zabbix_proxy'
- name: configure proxy service description
  lineinfile: dest=/etc/init.d/zabbix-proxy regexp="^DESC=.*" line='DESC="Zabbix proxy daemon"'

- name: configure ServerActive to be {{ zabbix_server }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_agentd.conf regexp="^ServerActive=.*" line='ServerActive={{ zabbix_server }}'
- name: configure agent Server to be {{ zabbix_server }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_agentd.conf regexp="^Server=.*" line='Server={{ zabbix_server }}'
- name: configure agent Hostname to be {{ ansible_hostname }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_agentd.conf regexp="^Hostname=.*" line='Hostname={{ ansible_hostname }}'
- name: configure proxy Server to be {{ zabbix_server }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_proxy.conf regexp="^Server=.*" line='Server={{ zabbix_server }}'
- name: configure proxy Hostname to be {{ ansible_hostname }}
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_proxy.conf regexp="^Hostname=.*" line='Hostname={{ ansible_hostname }}'

- name: configure database
  lineinfile: dest={{ zabbix_installdir }}/etc/zabbix_proxy.conf regexp="^DBName.*" line='DBName=/opt/zabbix/var/sqlite'

